Add typecheck.macro
jgierer12/awesome-babel-macros pull request #21
Opened 2020-06-07 18:21 UTC by vedantroy

Add typecheck.macro (https://github.com/vedantroy/typecheck.macro).

Note: I added a "Typescript" section because typecheck.macro is a macro that specifically only works with Typescript.

2020-06-15 09:58 UTC, jgierer12 requested changes
Thanks, just need some minor changes before I can merge this 🙂

2020-06-15 09:58 UTC, jgierer12 commented on readme.md
> +### Typescript
Please use the correct capitalization (`TypeScript`) here as well as in the table of contents.

If we're adding a TS section we might as well move `ts-nameof` in there from the General section.

2020-06-15 09:58 UTC, jgierer12 commented on readme.md
> +- [`typecheck.macro`](https://github.com/vedantroy/typecheck.macro): Automatically generate type-checker functions for Typescript types.
```suggestion
- [`typecheck.macro`](https://github.com/vedantroy/typecheck.macro): Automatically generate type-checker functions for TypeScript types
```

Just for consistency

2020-06-15 10:08 UTC, jgierer12 commented
By the way, I haven't read your whole readme yet but I didn't see a before/after example of the macro output ([like this](https://github.com/kentcdodds/import-all.macro#usage)). That's always one of the first things I look for when looking at a new macro to help me understand what it really does. You might want to consider putting something like that near the top of your readme.

2020-06-16 01:48 UTC, vedantroy commented
@jgierer12 I addressed your feedback!

2020-06-16 18:26 UTC, merged

2020-06-16 18:26 UTC, jgierer12 commented
Thanks 🙌